services:
  - type: web
    name: pearlcravino-website
    env: node
    buildCommand: npm install
    startCommand: npm server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
